from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.user_signup, name='user_signup'),
    path('vendor/signup/', views.vendor_signup, name='vendor_signup'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('user/dashboard/', views.user_dashboard, name='user_dashboard'),
    path('vendor/dashboard/', views.vendor_dashboard, name='vendor_dashboard'),
    path('admin-panel/', views.admin_dashboard, name='admin_dashboard'),
    path('add-product/', views.add_product, name='add_product'),
    path('edit-product/<int:pk>/', views.edit_product, name='edit_product'),
    path('delete-product/<int:pk>/', views.delete_product, name='delete_product'),
    path('cart/', views.view_cart, name='view_cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('orders/', views.order_history, name='order_history'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('products/search/', views.search_products, name='search_products'),
    path('product/<int:product_id>/rate/', views.rate_product, name='rate_product'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('admin/add-user/', views.admin_add_user, name='admin_add_user'),
    path('admin/edit-user/<int:user_id>/', views.admin_edit_user, name='admin_edit_user'),
    path('admin/delete-user/<int:user_id>/', views.admin_delete_user, name='admin_delete_user'),
    path('admin/add-vendor/', views.admin_add_vendor, name='admin_add_vendor'),
    path('admin/edit-vendor/<int:vendor_id>/', views.admin_edit_vendor, name='admin_edit_vendor'),
    path('admin/delete-vendor/<int:vendor_id>/', views.admin_delete_vendor, name='admin_delete_vendor'),
    path('admin/add-product/', views.admin_add_product, name='admin_add_product'),
    path('admin/edit-product/<int:product_id>/', views.admin_edit_product, name='admin_edit_product'),
    path('admin/delete-product/<int:product_id>/', views.admin_delete_product, name='admin_delete_product'),
    path('get-subcategories/<int:category_id>/', views.get_subcategories, name='get_subcategories'),
    # Wishlist URLs
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:wishlist_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('products/', views.product_list, name='product_list'),
]