# Generated by Django 5.2.1 on 2025-06-02 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='banner',
            field=models.ImageField(blank=True, upload_to='store_banners/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='store_logos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
