# Generated by Django 5.2.1 on 2025-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_product_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_keeping_unit',
            field=models.CharField(blank=True, help_text='Unique identifier for the product', max_length=50, null=True, unique=True),
        ),
    ]
