# Generated by Django 5.2.1 on 2025-05-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_orderitem_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
        ),
    ]
