# Generated by Django 5.2.1 on 2025-05-29 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_paymentmethod_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='carts_user_id_b1c689_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_items_cart_id_421c1e_idx',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.productvariant'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
    ]
